apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigtable-emulator-deployment
  labels:
    app: bigtable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bigtable
  template:
    metadata:
      labels:
        app: bigtable
    spec:
      containers:
        - name: bigtable-emulator
          image: gcr.io/google.com/cloudsdktool/cloud-sdk:emulators
          command: ["gcloud", "beta", "emulators", "bigtable", "start"]
          args: ["--project=local", "--host-port=0.0.0.0:8086"]
---
apiVersion: v1
kind: Service
metadata:
  name: bigtable-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  selector:
    app: bigtable